name: Watch Dog

on:
  schedule:
    - cron: "*/30 * * * *"  # Run every 30 minutes
  workflow_dispatch:

jobs:
  run-watchdog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.NAOMI_GITHUB_TOKEN }}  # Ensure we have push access

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Watch Dog
      env:
        NAOMI_GITHUB_TOKEN: ${{ secrets.NAOMI_GITHUB_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: python watchdog.py

    - name: Commit and Push Updated merge_log.txt
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add merge_log.txt
        git commit -m "Update merge_log.txt to track notified PRs" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.NAOMI_GITHUB_TOKEN }}