name: Watch Dog

on:
  # cron scheduling on running python script
  schedule:
    # setup running frequency
      # minute(0-59) hour(0-23) day-of-month(1-31) month(1-12) day-of-week(0-7)
      # "*/X" define frequency!
    - cron: "*/30 * * * *" # set to check once every 30 minute

  # allow manually running on github actions tab
  workflow_dispatch:

jobs:
  # define tasks and steps
  run-polling:
    runs-on: ubuntu-latest

    steps:
    # retrieve code from repository (giving access to yml)
    - name: Checkout code
      uses: actions/checkout@v2
    # install python with prebuilt setup from github actions
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    # install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # start running
    - name: Run Watch Dog
      env:
        NAOMI_GITHUB_TOKEN: ${{ secrets.NAOMI_GITHUB_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: python watchdog.py